aliyun-oss:
  access-key-id: yourAccessKeyId
  access-key-secret: yourAccessKeySecret
  bucket-name: yourBucketName
  bucket-url: yourBucketUrl
casbin:
  model-path: ./resource/rbac_model.conf
email:
  host: smtp.163.com
  is-ssl: true
  nickname: test
excel:
  dir: ./resource/excel/
jwt:
  signing-key: qmPlus
mysql:
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: gva
  max-idle-conns: 10
  password: Aa@6447985
  path: 127.0.0.1:3306
  username: root
qiniu:
  bucket: qm-plus-img
  secret-key: pgdbqEsf7ooZh7W3xokP833h3dZ_VecFXPDeG5JY
redis:
  db: 0
system:
  addr: 8888
  env: public
  use-multipoint: false
tencent-cos:
  secret-key: xxxxxxxx
zap:
  director: log
  encode-level: LowercaseColorLevelEncoder
  format: console
  link-name: latest_log
