captcha:
  key-long: 6
  img-width: 240
  img-height: 80
casbin:
  model-path: ./resource/rbac_model.conf
jwt:
  signing-key: qmPlus
localupload:
  local: true
  avatar-path: uploads/avatar
  file-path: uploads/file
log:
  prefix: '[GIN-VUE-ADMIN]'
  log-file: true
  stdout: DEBUG
  file: DEBUG
mysql:
  username: root
  password: Aa@6447985
  path: 127.0.0.1:3306
  db-name: qmPlus
  config: charset=utf8mb4&parseTime=True&loc=Local
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: false
qiniu:
  access-key: 25j8dYBZ2wuiy0yhwShytjZDTX662b8xiFguwxzZ
  secret-key: pgdbqEsf7ooZh7W3xokP833h3dZ_VecFXPDeG5JY
  bucket: qm-plus-img
  img-path: http://qmplusimg.henrongyi.top
redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 0
sqlite:
  username: ""
  password: ""
  path: db.db
  config: loc=Asia/Shanghai
  log-mode: true
system:
  use-multipoint: false
  env: public
  addr: 8888
  db-type: mysql
