name: gin-vue-admin ci&cd

on:
  push:
    branches: [ action-ci ]

jobs:

  build:
    name: Build
    runs-on: [ self-hosted ]
    steps:

    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Show files
      run: ls -la

    - name: Get dependencies
      run: |
        cd server
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: |
        go build -v .

