name: Go

on:
  push:
    branches: [ action-ci ]

jobs:

  build:
    name: Build
    runs-on: [ VM_0_11_centos ]
    steps:
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: |
        pwd
        ls -la
        cd server
        go build -v .

